# This workflow will render PDF files from the .tex-files in the Documents folder.
# For more information see: https://github.com/marketplace/actions/github-action-for-latex

name: Build LaTeX document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Documents/mysteriet-pa-malaroarna/main.tex
      - name: Upload PDF files
        uses: actions/upload-artifact@v4
        with:
          # Creates a file named documents.zip containing the rendered PDFs.
          name: documents
          # Adds all PDFs to the ZIP-archive.
          path: |
            *.pdf
